Small UX enhancements
dataiku/dss-plugin-nlp-visualization pull request #13
Opened 2021-03-31 10:04 UTC by Alexlandeau

- Renamed "Detected language column" to "Language column"
- Renamed "Categorical column" to "Split by column"
- Added number of words parameter
- Added color palette parameter
- Removed faded color from the palette

2021-03-31 10:04 UTC, Alexlandeau commented
CH62057

2021-03-31 15:43 UTC, alexcombessie requested changes

2021-03-31 15:43 UTC, alexcombessie commented on custom-recipes/nlp-visualization-wordcloud/recipe.json
> +      "getChoicesFromPython": true,
Forgot to update "Detected language column" -> "Language column" in the dynamic select

2021-03-31 15:43 UTC, alexcombessie commented on custom-recipes/nlp-visualization-wordcloud/recipe.json
> +      "label": "Display",
```suggestion
      "label": "Display parameters",
```

2021-03-31 15:43 UTC, alexcombessie commented on custom-recipes/nlp-visualization-wordcloud/recipe.json
> +      "name": "separator_display",
How about moving the display param section above subchart? To make sure subchart is last

2021-03-31 15:43 UTC, alexcombessie commented on custom-recipes/nlp-visualization-wordcloud/recipe.json
> +      "description": "A list of hexadecimal color codes",
```suggestion
      "description": "List of hexadecimal color codes or HTML color names to randomly color each word",
```

2021-03-31 15:43 UTC, alexcombessie commented on custom-recipes/nlp-visualization-wordcloud/recipe.json
> +      "defaultValue": ["#1F75B3", "#FF7F0F", "#2CA02B"]
IMO hex codes are a bit frightening for non-technical users. Could you have an option for users to use HTML color names? matplotlib has a function to convert one into the other

2021-04-01 16:52 UTC, alexcombessie commented on custom-recipes/nlp-visualization-wordcloud/recipe.json
> +      "description": "A list of colors to randomly color each word. Supported formats are X11 color names, hexadecimal color codes or matplotlib color shortcuts",
To make it fit on one line:
```suggestion
      "description": "List of colors to randomly color each word. Supported formats are hexadecimal color codes and matplotlib color names.",
```

2021-04-01 16:59 UTC, alexcombessie approved these changes

2021-04-01 17:14 UTC, merged